name: GitHub-Profile-Summary-Cards

on:
  create:
  push:
  schedule:
    - cron: "0 23 * * *"
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate
    
    steps:
      - uses: actions/checkout@v2
      - uses: vn7n24fzkq/github-profile-summary-cardsv@0.4.0-hotfix.3
        env:
          GITHUB_TOKEN: ${{ secrets.SUMMARY_CARDS_TOKEN }}
        with:
          username: ${{ github.repository_owner }}

         